"""Source-map generator: a deterministic markdown orientation map of a
white-box source tree, pushed into the sandbox before agents spawn.

Post-mortem driver: white-box specialists burned 10-20 turns re-deriving the
tree with ls/find/cat. This module walks the mounted source ONCE on the host
and emits a stable map (stack, API routes with exported HTTP methods, pages,
security-relevant files, process.env names) so the first specialist turn
starts from structure, not from zero.

Rules:
- Deterministic: same tree in, byte-identical map out (sorted everywhere).
- Honest: facts come from the files (exported function names, dependency
  lists); nothing is inferred beyond path conventions, and the header says
  to verify everything against the source.
- Never reads or echoes file contents beyond names and identifiers — env
  var NAMES only, no values; .env files are never opened.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

# Vendored/build output never helps orientation and can be huge.
SKIP_DIRS = {
    "node_modules", ".next", ".git", ".vercel", ".turbo", ".cache",
    "__pycache__", "coverage", "dist", "build", "out", "vendor",
}
MAX_FILES = 5_000
MAX_TREE_LINES = 200
MAX_LISTED = 12  # per keyword category / dependency dump
MAX_ENV_SCAN_BYTES = 512 * 1024
ENV_SCAN_SUFFIXES = {".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".vue", ".svelte"}

HTTP_METHODS = ("GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS")

_METHOD_RES: dict[str, tuple[re.Pattern[str], ...]] = {
    method: tuple(
        re.compile(rf"export\s+(?:async\s+)?{kind}\s+{method}\b")
        for kind in ("function", "const")
    )
    for method in HTTP_METHODS
}
_ENV_RE = re.compile(
    r"process\.env(?:\.([A-Za-z_][A-Za-z0-9_]*)"
    r"|\[\s*[\"']([A-Za-z_][A-Za-z0-9_]*)[\"']\s*\])"
)

# Framework label → dependency name (checked in this order; first hit wins).
_FRAMEWORK_PROBES = [
    ("Next.js", "next"),
    ("Nuxt", "nuxt"),
    ("SvelteKit", "@sveltejs/kit"),
    ("Remix", "@remix-run/react"),
    ("Astro", "astro"),
    ("Gatsby", "gatsby"),
    ("Angular", "@angular/core"),
    ("Express", "express"),
    ("Fastify", "fastify"),
    ("NestJS", "@nestjs/core"),
    ("React", "react"),
    ("Vue", "vue"),
    ("Svelte", "svelte"),
]

# Keyword inventory: category → path regex. Lead list, not a finding list.
_KEYWORD_CATEGORIES: list[tuple[str, re.Pattern[str]]] = [
    ("auth", re.compile(r"auth|login|session|jwt|token|passport|credential|oauth")),
    ("middleware", re.compile(r"middleware")),
    ("upload", re.compile(r"upload")),
    ("rate-limit", re.compile(r"rate[-_.]?limit|throttl")),
]


def generate_source_map(source_dir: Path) -> str:
    """Walk a source tree and render the deterministic markdown map."""
    source_dir = Path(source_dir)
    files = _source_files(source_dir)
    pkg = _load_package_json(source_dir)
    deps = _merged_deps(pkg)

    lines: list[str] = [
        f"# Source map — {pkg.get('name') or source_dir.name}",
        "",
        "> Generated by VulnEm from the mounted source. This is a generated",
        "> starting point — verify against the source before relying on any",
        "> detail in here.",
        "",
    ]

    lines += _stack_section(pkg, deps)
    app_routes = _app_router_routes(files, source_dir)
    pages_router = _pages_router_routes(files, source_dir)
    if app_routes or pages_router:
        lines += _routes_section(app_routes, pages_router)
        lines += _pages_section(files, source_dir)
    else:
        lines += _generic_tree_section(files, source_dir)

    lines += _keyword_section(files, source_dir)
    lines += _env_section(files)
    lines += [
        "## Not included",
        "",
        f"- Vendored/build directories ({', '.join(sorted(SKIP_DIRS))}).",
        "- File contents — this map only carries names, routes and identifiers.",
        "",
    ]
    return "\n".join(lines)


# -- collection helpers ---------------------------------------------------------


def _source_files(source_dir: Path) -> list[Path]:
    """Every regular file under source_dir (skips vendored/build dirs).

    Sorted by POSIX relative path so the map is deterministic on any OS.
    """
    out: list[tuple[str, Path]] = []
    if not source_dir.is_dir():
        return []
    for path in source_dir.rglob("*"):
        if path.is_dir():
            continue
        rel = path.relative_to(source_dir)
        if any(part in SKIP_DIRS for part in rel.parts):
            continue
        out.append((rel.as_posix(), path))
        if len(out) >= MAX_FILES:
            break
    return [p for _, p in sorted(out, key=lambda t: t[0])]


def _load_package_json(source_dir: Path) -> dict:
    path = source_dir / "package.json"
    if not path.is_file():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return {}
    return data if isinstance(data, dict) else {}


def _merged_deps(pkg: dict) -> dict[str, str]:
    merged: dict[str, str] = {}
    for key in ("dependencies", "devDependencies"):
        block = pkg.get(key)
        if isinstance(block, dict):
            merged.update({str(k): str(v) for k, v in block.items()})
    return merged


def _framework_line(pkg: dict, deps: dict[str, str]) -> str:
    runtime_deps = pkg.get("dependencies") or {}
    for label, dep in _FRAMEWORK_PROBES:
        if dep in deps:
            note = "" if dep in runtime_deps else " (dev)"
            return f"{label} ({dep} {deps[dep]}{note})"
    return "no known framework detected in package.json"


def _read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""


# -- route extraction ------------------------------------------------------------


def _exported_methods(path: Path) -> list[str]:
    """HTTP methods exported by a route file (function or const exports)."""
    text = _read_text(path)
    return [m for m in HTTP_METHODS if any(r.search(text) for r in _METHOD_RES[m])]


def _segment_after(parts: tuple[str, ...], marker: str) -> list[str] | None:
    """Path segments after the LAST ``marker`` directory segment, else None."""
    idx = max((i for i, p in enumerate(parts) if p == marker), default=-1)
    return None if idx < 0 else list(parts[idx + 1 :])


def _route_path(segments: list[str]) -> str:
    """App-router segments → URL path: ``[id]``→``:id``, ``[...slug]``→``:slug*``,
    route groups ``(x)`` dropped."""
    out: list[str] = []
    for seg in segments:
        if seg.startswith("(") and seg.endswith(")"):
            continue  # route groups don't appear in URLs
        if seg.startswith("[[...") and seg.endswith("]]"):
            out.append(":" + seg[5:-2] + "*")
        elif seg.startswith("[...") and seg.endswith("]"):
            out.append(":" + seg[4:-1] + "*")
        elif seg.startswith("[") and seg.endswith("]"):
            out.append(":" + seg[1:-1])
        else:
            out.append(seg)
    return "/" + "/".join(out)


def _app_router_routes(files: list[Path], source_dir: Path) -> list[dict]:
    """Every app-router route.ts/.js file with its exported HTTP methods."""
    routes: list[dict] = []
    for f in files:
        if f.name not in {"route.ts", "route.js"}:
            continue
        segments = _segment_after(f.relative_to(source_dir).parts, "app")
        if segments is None:
            continue
        routes.append({
            "route": _route_path(segments[:-1]),
            "methods": _exported_methods(f),
            "file": f.relative_to(source_dir).as_posix(),
        })
    routes.sort(key=lambda r: (r["route"], r["file"]))
    return routes


def _pages_router_routes(files: list[Path], source_dir: Path) -> list[str]:
    """Sorted URL paths from a pages/ directory (pages router)."""
    paths: list[str] = []
    for f in files:
        if f.suffix not in {".tsx", ".ts", ".jsx", ".js"}:
            continue
        segments = _segment_after(f.relative_to(source_dir).parts, "pages")
        if segments is None:
            continue
        stem = segments[-1].rsplit(".", 1)[0]
        if stem in {"_app", "_document", "_error"}:
            continue  # framework scaffolding, not testable pages
        paths.append(_route_path([*segments[:-1], stem]))
    return sorted(set(paths))


def _app_pages(files: list[Path], source_dir: Path) -> list[str]:
    """Sorted URL paths from app-router page.tsx/.jsx files."""
    paths: list[str] = []
    for f in files:
        if f.suffix not in {".tsx", ".jsx"} or f.name.split(".", 1)[0] != "page":
            continue
        segments = _segment_after(f.relative_to(source_dir).parts, "app")
        if segments is None:
            continue
        paths.append(_route_path(segments[:-1]))
    return sorted(set(paths))


# -- markdown sections -------------------------------------------------------------


def _stack_section(pkg: dict, deps: dict[str, str]) -> list[str]:
    lines = ["## Stack", ""]
    if pkg:
        header = f"- Package: {pkg.get('name', '?')}"
        if pkg.get("version"):
            header += f" {pkg['version']}"
        lines.append(header)
        lines.append(f"- Framework: {_framework_line(pkg, deps)}")
        if deps:
            listed = sorted(f"{name}@{ver}" for name, ver in deps.items())
            shown = ", ".join(listed[:MAX_LISTED])
            more = f" (+{len(listed) - MAX_LISTED} more)" if len(listed) > MAX_LISTED else ""
            lines.append(f"- Dependencies: {shown}{more}")
        scripts = pkg.get("scripts")
        if isinstance(scripts, dict) and scripts:
            names = sorted(scripts)
            shown = ", ".join(names[:MAX_LISTED])
            more = f" (+{len(names) - MAX_LISTED} more)" if len(names) > MAX_LISTED else ""
            lines.append(f"- Scripts: {shown}{more}")
    else:
        lines.append("- No package.json found (not a JavaScript/TypeScript project).")
    return [*lines, ""]


def _routes_section(app_routes: list[dict], pages_router: list[str]) -> list[str]:
    lines = ["## API routes (Next.js app router)", ""]
    if app_routes:
        lines += ["| Methods | Route | File |", "| --- | --- | --- |"]
        for r in app_routes:
            methods = ", ".join(r["methods"]) if r["methods"] else "(none exported)"
            lines.append(f"| {methods} | `{r['route']}` | {r['file']} |")
        lines.append("")
    if pages_router:
        lines += ["Pages-router API pages (one default export each — check the",
                  "file for the methods it handles):"]
        lines += [f"- `{p}`" for p in pages_router]
        lines.append("")
    lines.append("`[param]` path segments are shown as `:param`; catch-all"
                 " `[...slug]` as `:slug*`.")
    return [*lines, ""]


def _pages_section(files: list[Path], source_dir: Path) -> list[str]:
    pages = _app_pages(files, source_dir)
    if not pages:
        return []
    return ["## Pages", ""] + [f"- `{p}`" for p in pages] + [""]


def _generic_tree_section(files: list[Path], source_dir: Path) -> list[str]:
    """No Next.js structure recognized: degrade to a labeled file listing."""
    rels = sorted(f.relative_to(source_dir).as_posix() for f in files)
    lines = [
        "## File tree",
        "",
        "Stack not recognized as Next.js (no app-router route files, no pages/",
        "directory) — this is a generic file listing, not a route map.",
        "",
        "```",
    ]
    lines += rels[:MAX_TREE_LINES]
    if len(rels) > MAX_TREE_LINES:
        lines.append(f"... (+{len(rels) - MAX_TREE_LINES} more files)")
    return [*lines, "```", ""]


def _keyword_section(files: list[Path], source_dir: Path) -> list[str]:
    """Auth/middleware/upload/rate-limit files by keyword — a lead list."""
    lines = ["## Security-relevant files (keyword match — leads, not findings)", ""]
    found_any = False
    for category, pattern in _KEYWORD_CATEGORIES:
        hits = sorted(
            f.relative_to(source_dir).as_posix() for f in files
            if pattern.search(f.relative_to(source_dir).as_posix().lower())
        )
        if not hits:
            continue
        found_any = True
        shown = hits[:MAX_LISTED]
        more = f" (+{len(hits) - MAX_LISTED} more)" if len(hits) > MAX_LISTED else ""
        lines.append(f"- {category}: {', '.join(shown)}{more}")
    if not found_any:
        lines.append("(No auth/middleware/upload/rate-limit keyword matches.)")
    return [*lines, ""]


def _env_section(files: list[Path]) -> list[str]:
    """Names of process.env.* references across the codebase — names only."""
    names: set[str] = set()
    for f in files:
        if f.suffix not in ENV_SCAN_SUFFIXES:
            continue
        try:
            if f.stat().st_size > MAX_ENV_SCAN_BYTES:
                continue
        except OSError:
            continue
        for m in _ENV_RE.finditer(_read_text(f)):
            names.add(m.group(1) or m.group(2))
    if not names:
        return []
    return [
        "## Environment variables referenced (process.env.* — names only)",
        "",
        *(f"- {n}" for n in sorted(names)),
        "",
    ]
